/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class App {
    public String getGreeting() {
        return "Hello World!您好";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
    }
}
